// All supported languages with Web Speech API locale codes,
// BCP-47 TTS voices, display names, flags and UI strings.

export const LANGUAGES = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    speechLang: 'en-IN',
    ttsLang: 'en-IN',
    placeholder: 'Type your symptoms here...',
    listening: 'Listening... speak now',
    greeting: "Hello! I'm VaidyaAI, your health assistant.\n\nPlease tell me: What symptoms are you experiencing today?",
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    speechLang: 'ta-IN',
    ttsLang: 'ta-IN',
    placeholder: 'உங்கள் அறிகுறிகளை இங்கே தட்டச்சு செய்யுங்கள்...',
    listening: 'கேட்கிறேன்... இப்போது பேசுங்கள்',
    greeting: "வணக்கம்! நான் VaidyaAI, உங்கள் உடல்நல உதவியாளர்.\n\nதயவுசெய்து சொல்லுங்கள்: இன்று உங்களுக்கு என்ன அறிகுறிகள் உள்ளன?",
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    speechLang: 'hi-IN',
    ttsLang: 'hi-IN',
    placeholder: 'अपने लक्षण यहाँ लिखें...',
    listening: 'सुन रहा हूँ... अभी बोलें',
    greeting: "नमस्ते! मैं VaidyaAI हूँ, आपका स्वास्थ्य सहायक।\n\nकृपया बताएं: आज आपको क्या लक्षण हो रहे हैं?",
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    speechLang: 'ml-IN',
    ttsLang: 'ml-IN',
    placeholder: 'നിങ്ങളുടെ ലക്ഷണങ്ങൾ ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
    listening: 'ശ്രദ്ധിക്കുന്നു... ഇപ്പോൾ സംസാരിക്കൂ',
    greeting: "നമസ്കാരം! ഞാൻ VaidyaAI ആണ്, നിങ്ങളുടെ ആരോഗ്യ സഹായി.\n\nദയവായി പറയൂ: ഇന്ന് നിങ്ങൾക്ക് എന്ത് ലക്ഷണങ്ങളാണ് ഉള്ളത്?",
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    speechLang: 'te-IN',
    ttsLang: 'te-IN',
    placeholder: 'మీ లక్షణాలను ఇక్కడ టైప్ చేయండి...',
    listening: 'వినడం జరుగుతోంది... ఇప్పుడు మాట్లాడండి',
    greeting: "నమస్కారం! నేను VaidyaAI, మీ ఆరోగ్య సహాయకుడు.\n\nదయచేసి చెప్పండి: నేడు మీకు ఏ లక్షణాలు ఉన్నాయి?",
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    speechLang: 'kn-IN',
    ttsLang: 'kn-IN',
    placeholder: 'ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    listening: 'ಆಲಿಸುತ್ತಿದ್ದೇನೆ... ಈಗ ಮಾತನಾಡಿ',
    greeting: "ನಮಸ್ಕಾರ! ನಾನು VaidyaAI, ನಿಮ್ಮ ಆರೋಗ್ಯ ಸಹಾಯಕ.\n\nದಯವಿಟ್ಟು ಹೇಳಿ: ಇಂದು ನಿಮಗೆ ಯಾವ ರೋಗಲಕ್ಷಣಗಳಿವೆ?",
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    speechLang: 'fr-FR',
    ttsLang: 'fr-FR',
    placeholder: 'Tapez vos symptômes ici...',
    listening: 'Écoute... parlez maintenant',
    greeting: "Bonjour! Je suis VaidyaAI, votre assistant santé.\n\nVeuillez me dire: Quels symptômes ressentez-vous aujourd'hui?",
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    speechLang: 'de-DE',
    ttsLang: 'de-DE',
    placeholder: 'Geben Sie hier Ihre Symptome ein...',
    listening: 'Höre zu... bitte sprechen',
    greeting: "Hallo! Ich bin VaidyaAI, Ihr Gesundheitsassistent.\n\nBitte sagen Sie mir: Welche Symptome haben Sie heute?",
  },
  {
    code: 'zh',
    name: 'Mandarin',
    nativeName: '中文',
    flag: '🇨🇳',
    speechLang: 'zh-CN',
    ttsLang: 'zh-CN',
    placeholder: '在此输入您的症状...',
    listening: '正在聆听...请开始说话',
    greeting: "你好！我是VaidyaAI，您的健康助手。\n\n请告诉我：您今天有哪些症状？",
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    speechLang: 'ko-KR',
    ttsLang: 'ko-KR',
    placeholder: '여기에 증상을 입력하세요...',
    listening: '듣고 있어요... 지금 말하세요',
    greeting: "안녕하세요! 저는 VaidyaAI, 당신의 건강 도우미입니다.\n\n오늘 어떤 증상이 있으신가요?",
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    speechLang: 'ja-JP',
    ttsLang: 'ja-JP',
    placeholder: 'ここに症状を入力してください...',
    listening: '聞いています…話してください',
    greeting: "こんにちは！私はVaidyaAI、あなたの健康アシスタントです。\n\n今日どんな症状がありますか？",
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳',
    speechLang: 'vi-VN',   // Web Speech API
    ttsLang: 'vi-VN',      // matches backend TTS mapping
    placeholder: 'Nhập các triệu chứng của bạn ở đây...',
    listening: 'Đang nghe... hãy nói bây giờ',
    greeting: "Xin chào! Tôi là VaidyaAI, trợ lý sức khỏe của bạn.\n\nVui lòng cho tôi biết: Hôm nay bạn gặp những triệu chứng gì?",
}
]

export const LANG_MAP = Object.fromEntries(LANGUAGES.map(l => [l.code, l]))

export function getLang(code) {
  return LANG_MAP[code] || LANG_MAP['en']
}
